services:
  wordpress:
    image: wordpress:latest
    volumes:
      - /mnt/efs/wordpress:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: <Endpoint DB>
      WORDPRESS_DB_USER: <Master user DB>
      WORDPRESS_DB_PASSWORD: <Master password DB>
      WORDPRESS_DB_NAME: <Name DB>
      WORDPRESS_TABLE_CONFIG: wp_ | sudo tee /mnt/efs/docker-compose.yaml
