echo "version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - /mnt/efs/wordpress:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: <Ednpoint do DB>
      WORDPRESS_DB_USER: <Master user do DB>
      WORDPRESS_DB_PASSWORD: <Master password do DB>
      WORDPRESS_DB_NAME: <Initial Name do DB>
      WORDPRESS_TABLE_CONFIG: wp_" | sudo tee /mnt/efs/docker-compose.yml
cd /mnt/efs && sudo docker-compose up -d
